### ISSUE TITLE
vercel deployment

### ISSUE THREAD

**Issue by towkd** [SunoApi/SunoApi#1]
Can your APP be deployed on Vercle?

**Comment by SunoApi** [comment]
> Can your APP be deployed on Vercle?

Hi, I just tested the Vercel, will prompt error: Unable to find any supported Python versions ,Vercel is suitable for front-end static project deployment, the recommended use of Zeabur direct deployment .

**Comment by tulong-co** [comment]
主页模板不好看

**Comment by SunoApi** [comment]
> 主页模板不好看

你可以自己改好看的
