### ISSUE TITLE
Request for Assistance with Suno API Script Cookie Lifespan Issue

### ISSUE THREAD

**Issue by David4Lesage** [SunoApi/SunoApi#4]
I came across your GitHub repository regarding an unofficial Suno API. In fact, I've developed a Python script that automatically downloads songs from Suno using a prompt file and seleniumbase chromewebdriver. My current issue lies with the lifespan of cookies as they expire exactly after 1 week. If you could kindly assist me with this, I would even buy you a coffee if necessary.

**Comment by SunoApi** [comment]
> I came across your GitHub repository regarding an unofficial Suno API. In fact, I've developed a Python script that automatically downloads songs from Suno using a prompt file and seleniumbase chromewebdriver. My current issue lies with the lifespan of cookies as they expire exactly after 1 week. If you could kindly assist me with this, I would even buy you a coffee if necessary.

I encounter the situation you mentioned, it is unavoidable.  Now, I manually change cookies when prompted Unauthorized, because I have created an interface where cookies can be modified.  I'm sorry I can't help you right now.
