### ISSUE TITLE
为什么总是报‘Suno AI 音乐歌曲生成提交失败：Unauthorized’

### ISSUE THREAD

**Issue by liyunnnn** [SunoApi/SunoApi#5]
如题，尝试过关掉suno官网浏览器、退出登录，但是还是会遇到Suno AI 音乐歌曲生成提交失败：Unauthorized这个报错，怎么解决

**Comment by SunoApi** [comment]
不能退出的一旦退出你的session就无效了，需要重新登录获取新的session和cookie，获取后关闭页面就好了。每登录一次有效期是7天，到期了如果浏览器打开着官网页面会强制退出要求重新登录。另外不要用Firefox获取Cookie，经过测试Firefox下获取的Cookie中间带有特殊符号填写到里面请求直接返回401 Unauthorized，用Chrome获取Cookie就没这个问题。

**Comment by liyunnnn** [comment]
> 不能退出的一旦退出你的session就无效了，需要重新登录获取新的session和cookie，获取后关闭页面就好了。每登录一次有效期是7天，到期了如果浏览器打开着官网页面会强制退出要求重新登录。另外不要用Firefox获取Cookie，经过测试Firefox下获取的Cookie中间带有特殊符号填写到里面请求直接返回401 Unauthorized，用Chrome获取Cookie就没这个问题。

我也尝试过只是关闭页面，但还是会报一样的错误...我用的是chrome浏览器。另外我点歌曲生成和保存信息的时候在控制台的network下都没有看到接口请求这个正常吗？

**Comment by SunoApi** [comment]
总结：一般情况下获取的cookie信息正确，没有在其他地方登录是都可以在这里面正常使用的。
0、这个streamlit开发框架是用的websocket前后台通讯的，不是传统的xhr请求方式所以看不到。
1、用chrome浏览器获取cookie，获取不带suno.com域名的cookie数据，整个cookie字段值复制。
2、从其他第三方链接跳转注册suno账号后清空浏览器cookie缓存数据再获取以免带上其他无效数据。
3、登录成功获取到cookie信息后关闭其他所有登录的suno网站页面，如还提示则重启一次服务后再试。
